name: pokemon_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: 8.1.0
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  get: ^4.6.5
  retrofit: ^3.3.1
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  flutter_staggered_grid_view: ^0.6.2
  floor_generator: ^1.4.2
  floor: ^1.4.2
  json_class: ^2.1.4+1
  sqflite: ^2.2.8+4
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  retrofit_generator: ^4.2.0
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true

  assets:
  - assets/pikachu_placeholder.png
  - assets/pokemon_logo.png
  - assets/professor_oak.png
  - assets/favorites.png
  - assets/gotcha.png
  - assets/pokedex.jpeg
  - assets/lottie/pokeball.json

  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/fonts/pokemon_solid.ttf
